package logemi.ttdiary;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import logemi.ttdiary.view.AppFrame;

public class App {
    public static void main(String[] args) {
      new AppFrame();
    }
}
